# This rule is not used by the project autolabeller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to autolabeller.autolabeller.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autolabeller
    app.kubernetes.io/managed-by: kustomize
  name: classificationrule-viewer-role
rules:
- apiGroups:
  - autolabeller.autolabeller.github.com
  resources:
  - classificationrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autolabeller.autolabeller.github.com
  resources:
  - classificationrules/status
  verbs:
  - get
