apiVersion: autolabeller.autolabeller.github.com/v1alpha1
kind: ClassificationRule
metadata:
  labels:
    app.kubernetes.io/name: autolabeller
    app.kubernetes.io/managed-by: kustomize
  name: classificationrule-sample
spec:
  targetKind: Pod
  Match:
    commonMatch:
      Namespace:  "superfunnynamespace"
      Name: "superfunnyname"

    podMatch:
      Images: 
        - "busybox:latest"
      CPURequests:
        Min: "100m"
        Max: "500m"
      MemoryRequests:
        Min: "128Mi"
        Max: "512Mi"

  Labels:
    superfunnytestlabel: "didLaugh"

  ConflictPolicy: Merge
  Suspend: false